# pages-collection
# a Jekyll Digital Collection Generator
# designed for GH-Pages

# Site settings

# title of site appears in banner
title: The Symposium Collection
# tagline appears in banner
tagline: A NEW DIGITAL ARCHIVE
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "A smattering of things from Washington State University and University of Idaho archives."
# keywords appear in meta tags
keywords: "university of idaho, digital collections, digital humanities"
# creator of the digital collection, to appear in meta tags
author: elle4
# creator contact email for meta tags
email: chanelle.fournier@wsu.edu
# collection project date, when did you publish this
collection-date: "2018"

# url is your gh-pages base, username.github.io
url: https://elle4.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: /symposiumcollection2
# repository is the github repository's full url
repository: https://github.com/elle4/symposiumcollection2

# google services [optional!]
# leave these blank or comment out to NOT include google code
# google-tracking-id: "UA-74844011-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

# build settings
permalink: pretty

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
